swagger: '2.0'
info:
  version: '1.0'
  title: O2G API
  description: |-
    Данный OAS2 (Swagger 2) файл представляет собой настоящий API, который находится по адресу: `http://192.168.0.214:8081/restapi/v1`.

    Для получения информации об аутентификации нажмите на схему безопасности `apikey` на боковой панели редактора.
  contact:
    name: O2G
    url: 'https://o2g.web-dew.space'
  license:
    name: ''
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apikey:
    type: apiKey
    in: header
    name: X-TOKEN-BEARER
    description: 'X-TOKEN-BEARER - токен, используемый в хэдере запросов'
paths:
  /oauth/token:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              access_token:
                type: string
              expires_in:
                type: integer
              scope:
                type: string
              token_type:
                type: string
              user_exists:
                type: boolean
            required:
              - access_token
              - expires_in
              - scope
              - token_type
              - user_exists
          examples:
            application/json:
              access_token: 02RXD8JKPXOTTBFQRDH4MW
              expires_in: 7200
              scope: all
              token_type: Bearer
              user_exists: true
      description: |
        ### Авторизация по номеру телефона (запрос на подтверждение секрета)
        Метод должен вернуть токен на основании секрета.

        Возможные ошибки:
        * 4370 - некорректная пара id и secret
        * 6114 - параметры имеют недопустимое форматирование или тип данных
        * Некорректный тип запроса или запрашиваемый доступ
      summary: Авторизация по номеру телефона (запрос на подтверждение секрета)
      parameters:
        - in: query
          name: client_id
          type: string
          description: Номер телефона или адрес почты пользователя
          required: true
        - in: query
          name: client_secret
          type: string
          required: true
          description: Полученный секрет
        - in: query
          name: scope
          type: string
          description: |
            Запрашиваемый доступ == all
          required: true
      tags:
        - Авторизация
      operationId: oauth-token
  /oauth/credentials:
    get:
      responses:
        '204':
          $ref: ''
        '500':
          $ref: '#/responses/internal-error:2330'
      description: |
        ### Авторизация по номеру телефона или почте (запрос на отправку секрета)
        Должен быть передан на вход только 1 элемент: или почта, или номер телефона.
        В результате выполнения метода должен быть сгенерирован и возвращён секрет для последующего использования методов. Секрет должен быть возвращён:
        * в случае телефона - в виде кода в СМС
        * в случае почты  - в виде кода в письме

        Возможные ошибки:
        * 2330 - внутренняя ошибка сервера
        * 5839 - не предоставлены необходимые параметры
        * 6114 - параметры имеют недопустимое форматирование или тип данных
      summary: Авторизация по номеру телефона или почте
      parameters:
        - in: query
          name: email
          type: string
          description: Адрес почты
        - in: query
          name: phone
          type: integer
          description: Номер телефона
      tags:
        - Авторизация
      operationId: oauth-credentials
  /auth:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              access_token:
                type: string
            required:
              - access_token
          examples:
            application/json:
              access_token: SZVVSHDXP3IJIP1X94HK7Q
      summary: Авторизация по паролю
      description: |
        ### Авторизация по паролю (необходим зарегистрированный аккаунт)
        Проводит авторизацию пользователя по указанным данным.

        Возможные ошибки:
        * 2330 - внутренняя ошибка сервера
        * 4370 - пользователь не был авторизован, не найдено такой пары phone/email и password
        * 5839 - не предоставлены необходимые параметры
        * 6114 - параметры имеют недопустимое форматирование или тип данных
      parameters:
        - in: query
          name: phone
          type: integer
          required: true
          description: Номер телефона пользователя
        - in: query
          name: password
          type: string
          required: true
          description: Пароль пользователя
      tags:
        - Авторизация
      operationId: auth
  '/spaces/{id}':
    get:
      summary: Получить  информацию о площадке
      operationId: get-spaces-id
      responses:
        '200':
          description: Возвращает массив площадок
          schema:
            type: array
            items:
              $ref: '#/definitions/Space'
      description: |-
        Получить информацию о площадке по заданному ID площадки.

        Если текущий пользователь не является владельцем площадки, то данные не должны быть предоставлены.
      tags:
        - Площадки
      parameters: []
      consumes:
        - application/json
      produces:
        - application/json
    parameters:
      - type: integer
        name: id
        in: path
        required: true
        description: ID площадки
    put:
      summary: Изменить информацию о площадке
      operationId: put-spaces-id
      responses:
        '200':
          description: Возвращает площадку с обновленным расписанием
          schema:
            $ref: '#/definitions/Space'
      description: |-
        Изменить информацию о площадке (изменение расписания работы площадки).

        Если текущий пользователь не является владельцем площадки, то данные не должны быть изменены.
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/ScheduleTemplate'
      tags:
        - Площадки
  /spaces:
    get:
      summary: Получить список площадок
      operationId: get-spaces
      responses:
        '200':
          description: Возвращает массив площадок
          schema:
            type: array
            items:
              $ref: '#/definitions/Space'
      description: 'Получить весь список площадок, которые принадлежат пользователю (владельцу площадки)'
      tags:
        - Площадки
      parameters: []
      consumes:
        - application/json
      produces:
        - application/json
    parameters: []
  /spaces/create:
    parameters: []
    post:
      summary: Создать площадку в системе
      operationId: post-spaces-create
      responses:
        '201':
          description: Возвращает созданный объект площадки
          schema:
            $ref: '#/definitions/Space'
      description: |-
        Создать площадку в системе.

        Если у текущего пользователя нет роли "Владелец площадки", то операция создания не должна быть выполнена.
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Space'
          description: ''
      tags:
        - Площадки
  /bookings:
    parameters: []
    get:
      summary: Получить список бронирований
      tags:
        - Бронирования
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      operationId: get-bookings
      description: |-
        ### Получить список бронирований по площадке

        Метод должен возвращать список бронирований, относящихся к указанной площадке пользователя. Если параметр не задан - ко всем площадкам текущего пользователя.

        Должна присутствовать информация о номере забронированного места, времени бронирования, цене и статусе.

        Если текущий пользователь не является владельцем указанной площадки, то данные не должны быть предоставлены.
      parameters:
        - type: integer
          in: query
          name: space_id
          description: ID площадки
  /places:
    get:
      summary: Получить список мест на площадке
      tags:
        - Места
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      operationId: get-places
      description: |
        ### Получить список мест площадки с учётом фильтров

        Метод должен возвращать список мест на указанной площадке, согласно входным фильтрам.

        Статус забронировано ли место должен быть получен из таблицы places по текущей дате и времени.

        Расписание работы должно быть получено из таблицы schedule_template. Если у коворкинга круглосуточный режим - должен быть заполнен параметр all_time и пустой массив schedule_template, иначе - наоборот.
  '/places/{id}':
    get:
      summary: Получить информацию о месте
      tags:
        - Места
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      operationId: get-places-id
      description: |-
        Получить информацию о месте по заданному ID площадки.

        Если текущий пользователь не является владельцем площадки, то данные не должны быть предоставлены.
    parameters:
      - type: string
        name: id
        in: path
        required: true
parameters:
  limit:
    name: limit
    in: query
    description: This is how it works.
    required: false
    type: integer
    maximum: 100
  skip:
    name: skip
    in: query
    required: false
    type: string
definitions:
  Space:
    title: Space
    description: Модель площадки
    type: object
    properties:
      id:
        type: string
        description: ID площадки (PK)
        readOnly: true
      name:
        type: string
        description: Название площадки
        example: TopWork
      latitude:
        type:
          - number
        description: Широта
        format: float
      longitude:
        type:
          - number
        description: Долгота
        format: float
      address:
        type: string
        description: Адрес прописью
        example: 'Москва, ул. Садовников, д. 15'
      description:
        type: string
        description: |
          Описание площадки
      schedule_template:
        type: array
        items:
          $ref: '#/definitions/ScheduleTemplate'
      photo:
        type: array
        description: Фотографии площадки
        items:
          type: string
    required:
      - id
      - name
      - latitude
      - longitude
      - address
      - description
      - schedule_template
  ScheduleTemplate:
    type: object
    title: ScheduleTemplate
    description: Модель шаблона расписания для площадки
    properties:
      weekday:
        type: integer
      start_time:
        type:
          - string
        format: time
      end_time:
        type: string
        format: time
  Place:
    title: Place
    type: object
    x-tags:
      - Place
    description: Модель рабочего места
    properties:
      id:
        type: integer
        readOnly: true
      place_type:
        type: string
      place_number:
        type: string
      description:
        type: string
      space_id:
        type: integer
      place_facilities:
        type: array
        items:
          $ref: '#/definitions/PlaceFacility'
      price:
        type: number
        format: float
      price_type:
        type: string
      photo:
        type: array
        items:
          $ref: '#/definitions/Picture'
    required:
      - id
      - place_type
      - space_id
      - price
      - price_type
  Picture:
    title: Picture
    type: object
    x-tags:
      - Picture
    description: Модель картинки / фотографии
    properties:
      id:
        type: integer
        description: ID картинки (PK)
        readOnly: true
      url:
        type: string
        description: Ссылка на картинку
      sort:
        type: integer
        description: Порядок сортировки
    required:
      - id
      - url
  PlaceFacility:
    title: PlaceFacility
    type: object
    x-tags:
      - Place
    description: Модель дополнительного оборудования на рабочем месте
    properties:
      id:
        type: integer
        description: ID оборудования (PK)
        readOnly: true
      name:
        type: string
        description: Название
    required:
      - id
      - name
tags:
  - name: Авторизация
    description: Методы для осуществления авторизации в системе
  - name: Площадки
    description: Методы для выполнения операций над объектами типа `Space`
  - name: Бронирования
    description: Методы для выполнения операций над объектами типа `Booking`
  - name: Места
    description: Методы для выполнения операций над объектами типа `Place`
basePath: /restapi/v1
responses:
  'internal-error:2330':
    description: |
      Внутренняя ошибка сервера
    schema:
      type: object
      properties:
        code:
          type: integer
        title:
          type: string
        message:
          type: string
        action:
          type: string
    examples:
      application/json:
        code: 2330
        title: Internal Server Error
        message: Внутренняя ошибка сервера
host: '192.168.0.214:8081'
security:
  - apikey: []
